name: flutter_core
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

    # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Network Connection
  dio: ^5.7.0
  http_parser: ^4.0.2
  connectivity_plus: ^6.1.2
  network_info_plus: ^6.1.4

  # Responsive UI
  flutter_screenutil: ^5.9.3

  # Utils
  intl: ^0.20.2
  fluttertoast: ^8.2.10
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  lottie: ^3.3.1
  crypto: ^3.0.6
  shimmer: ^3.0.0
  device_info_plus: ^11.2.1
  animations: ^2.0.11
  dropdown_button2: ^2.3.9
  flutter_html: ^3.0.0

  # Image of File picker
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.5

  # This app utils
  readmore: ^3.0.0
  grouped_list: ^6.0.0
  pin_code_fields: ^8.0.1
  easy_date_timeline: ^2.0.6
  control_style: ^0.1.0
  carousel_slider: ^5.0.0
  mobile_scanner: ^7.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.8.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
